// Generated by CoffeeScript 1.6.3
(function() {
  var caddy, expect, origNextTick, sinon;

  expect = require('chai').expect;

  sinon = require('sinon');

  origNextTick = process.nextTick;

  caddy = require('../dist/caddy');

  describe('function wrapping', function() {
    it('should wrap process.nextTick', function() {
      return expect(process.nextTick).to.not.equal(origNextTick);
    });
    return it('should call original process.nextTick', function(done) {
      var spy;
      spy = sinon.spy(origNextTick);
      console.log(spy.callCount);
      return process.nextTick(function() {
        console.log(spy.callCount);
        return done();
      });
    });
  });

}).call(this);
